### ISSUE TITLE
"No SASL authentication mechanism available" error in 0.8.7

### ISSUE THREAD

**Issue by QbNc** [yaxim-org/yaxim#112]
I have been using yaxim with fastmail's jabber / xmpp service for months with no problems. two android devices and two separate fastmail accounts.

Updating to latest version of (January 30 2014 in android market, apparently v0.8.7)  throws "No SASL authentication mechanism available" error and prevents me from connecting to Fastmail's jabber service

Another android device, also with yaxim, but without auto-updates continued to work with a (different) fastmail account, until I manually updated yaxim to the latest version. Then it stopped working too, throwing the same SASL error.

Fastmail docs say they use SSL/TLS but do NOT use SASL. I see no option in yaxim to disable SASL. Please help.

**Comment by cyttorak** [comment]
I'm having the same error.
