### ISSUE TITLE
Searching messages

### ISSUE THREAD

**Issue by weiss** [yaxim-org/yaxim#129]
Wish list item: If it would be possible to search through messages (or to "filter" them using search strings), that would be awesome :-)

(Please just close this issue if that seems too hard/uninteresting to implement.)

**Comment by ge0rg** [comment]
Implemented in 62be37e718f40b18488a22aeb0ffa3490aebafa4 and ab6fd987c268b93dd849892c7ac083a3ff817461,  will be part of the next release.
