### ISSUE TITLE
asmack-android-8.jar

### ISSUE THREAD

**Issue by dhcai** [yaxim-org/yaxim#168]
Can you provide the source code of  asmack-android-8.jar？

Because I want to modify the part of the code. Thank you!

**Comment by pingothedoer** [comment]
Kindly provide the source code of asmack-android-8.jar because it has some modifications and fixes in original smack files and i need to modify some classes but if i download it from http://asmack.freakempire.de/0.8.6/ , it has original files not the custom ones.

**Comment by ge0rg** [comment]
My above comment lists the github repository and exact commit revision of the smack source code used in yaxim.

**Comment by pingothedoer** [comment]
Thnx, the commit has 7 folders. Which one i have to use,,,i guess the "source" folder in the root directory ??

**Comment by miighty** [comment]
Hi,

Is there a version of yaxim with smack 4.1integrated?

**Comment by pingothedoer** [comment]
I think yaxim already has 4.1...

**Comment by miighty** [comment]
It currently supports asmack 0.86, it doesn't support snacks 4.1 methods

**Comment by ge0rg** [comment]
yaxim is based on smack 3.x, there is a patch-set by @Flowdalic that imports smack4, but I need to find some time to review and test it.

**Comment by miighty** [comment]
Could you please direct me to the patch ge0rg?
It will save me a huge amount of time

**Comment by ge0rg** [comment]
You can find the code in the smack41muc branch on flow's repo:

https://github.com/Flowdalic/yaxim/tree/smack41muc

**Comment by jramirezmx** [comment]
this is correct ge0rg, thank you very much, it works me your post.

Sorry my English not good.
