### ISSUE TITLE
offline messages are lost

### ISSUE THREAD

**Issue by chandraveerr** [yaxim-org/yaxim#171]
while chating if internet connection of one client goes down the other client still shows it online and messages sent at that time by connected client are lost. Is there a way to rectify this?

**Comment by mbrethes** [comment]
I'm experiencing offline message drops chatting from a yax.im account to a riseup.net account.

Is there any way to store undelivered messages until the recipient finally goes online and receives them? Is that server dependent on the emitter side or on the receiver side?

How long the "offline" time may be until message is dropped?
