### ISSUE TITLE
yax.im: XEP-0191 Blocking Command

### ISSUE THREAD

**Issue by solarnoid** [yaxim-org/yaxim#193]
Please add server feature to better serve secure clients like conversations.  Please update yaxim client

**Comment by solarnoid** [comment]
.

**Comment by ge0rg** [comment]
Prosody has [mod_blocking](https://modules.prosody.im/mod_blocking.html), which is alpha quality and [mod_blocklist](https://prosody.im/doc/modules/mod_blocklist) which is of unknown quality.

I'm sitting on [a large number of prosody bug reports](https://prosody.im/issues/list?sort=id-asc&q=state%3Dopen+reporter%3Dge0rg) and I'm hesitant to add more untested modules to the server.

I'll have a look at this issue once the majority of the open bugs with yax.im has been resolved.

**Comment by ge0rg** [comment]
Installing mod_blocklist on yax.im now.

> Zash> It's the best module ever.
