### ISSUE TITLE
Special server for Russia

### ISSUE THREAD

**Issue by sergey-feo** [yaxim-org/yaxim#243]
Hi all!
Excuse me for my poor English please :-)

I am not sure if it is right place to write about yax.im server, excuse me for possible error please.

New Russian laws can lead to blocking yax.im server in Russia (they require identification with real mobile phone number):
http://ivo.garant.ru/#/document/71732812/paragraph/1:0
http://publication.pravo.gov.ru/Document/View/0001201811060001?index=1&rangeSize=1

But some people in Russia still want to use XMPP :-)  Can you open second server (yax-ru.im, for example) that will satisfy Russian goverment's requirements and so be legal in Russia please?

With best regards, Sergey

**Comment by ge0rg** [comment]
I'm sorry, this is very much out of scope. There is a number of Russian XMPP servers, so you should just register on one of those.
