### ISSUE TITLE
Fefature req. MUC. Dont send me "<my_user_name> has set the subject to: ... " on each reconnect.

### ISSUE THREAD

**Issue by dvs13** [yaxim-org/yaxim#245]
On each reconnect to server i receive message from all MUC where my status is moderator
"<my_user_name> has set the subject to: ... "

I can about 5 MUC.
when i travel on undergraund my phone reconnect about 10 times.
I receive ~50 spam mesages.

Please add customization for off this messages.

**Comment by ge0rg** [comment]
This smells very much like an XMPP server that's not following the protocol right. Which version of yaxim are you using? Have you tried the [latest nightly build](https://yaxim.org/archive/builds/yaxim-gl-2019-09-13.apk)?

Could you please enable "SMACK debugging" in the options and provide a logcat excerpt from the messages you receive on join? Or maybe invite me (xmpp:georg@yax.im) into one of those MUCs (and possibly make me an admin)?

**Comment by dvs13** [comment]
I update ejabberd to actual version and problem does not appear.
