### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by licaon-kter** [yaxim-org/yaxim#256]
...and build a Nightly so I can see them in context.

**Comment by ge0rg** [comment]
Here is a nightly with updated translations: https://yaxim.org/archive/builds/yaxim-gl-2020-03-29.apk

**Comment by licaon-kter** [comment]
Thanks, but why not pull them here too?

**Comment by ge0rg** [comment]
Whoops, sorry. Forgot to push the code, will do ASAP. Are you able to test it with the APK or do you want to build your own?

**Comment by licaon-kter** [comment]
Yes, the apk is ok, translation looks fine, thanks.
