### ISSUE TITLE
Notification of the new version of yaxim

### ISSUE THREAD

**Issue by Kashcheyeu** [yaxim-org/yaxim#262]
I install yaxim from Nightly Builds (https://yaxim.org/archive/builds/). Can I get a notification when a new version is released so that I can update yaxim immediately?
Thank you for this wonderful client.

**Comment by ge0rg** [comment]
I know that not everyone likes Google, but there is also f-droid (where somebody needs to fix the yaxim build), and I don't want to implement a function that will phone home just to learn the newest version of yaxim. Sorry.
