### ISSUE TITLE
 Implement receive custom emoticons on XMPP using XEP-0231: Bits of Binary

### ISSUE THREAD

**Issue by Kashcheyeu** [yaxim-org/yaxim#263]
Adding support for getting custom emoticons in XMPP using XEP-0231: Bits of Binary, as done in Pidgin.
https://developer.pidgin.im/ticket/5627

**Comment by ge0rg** [comment]
I don't see this as still relevant in today's times. For Emoji, you can just Unicode (which covers a huuuuge number of use cases), and for stickers and the like you can use image sharing via [XEP-0363](https://xmpp.org/extensions/xep-0363.html), which is already implemented in yaxim.

The latter only lacks support for animated gifs, inline video and direct pasting from modern keyboard apps.
