### ISSUE TITLE
Add latest version to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [yaxim-org/yaxim#271]
What's missing from muc log:
* smack 4.3.5-SNAPSHOT and jxmpp 0.6.4-SNAPSHOT: "there is a reason for using jxmpp and smack snapshots, I've got a bunch of commits there that are not possible to upstream" (also `-SNAPSHOTs` tend to disappear at random)
* "4.4 requires a higher android sdk level"
* "the deviation between official smack/jxmpp and forks is mainly of political nature...pushing my changesets to my github"  Done?
* "no "non-Google" flavor yet, I tried to compartmentalize the FCM code (and might have to do the same with the InstallReferer code)"

More?

**Comment by ge0rg** [comment]
* My Smack changes are in https://github.com/ge0rg/smack4/tree/4.3.5-SNAPSHOT - I don't see a chance to upstream them, but I'm not hiding them from f-droid either ;) you should be able to `gradle install` it right before the yaxim build, it will be stored in `~/.m2/repository/` and loaded by the yaxim build
* My jxmpp changes are in https://github.com/ge0rg/jxmpp - same comment
* I haven't looked into Smack 4.4 yet, and probably won't for some more years
* I've just created a no-Google no-Push flavor of the app, ae952502d77b35499268461849230da1dee46f08 with `yaximFreeRelease` and `brunoFreeRelease`.

Let me know what else you need.

**Comment by licaon-kter** [comment]
Will try, thanks for the updated info

**Comment by licaon-kter** [comment]
Pls update what commit this submodule should use as https://github.com/ge0rg/MemorizingTrustManager/tree/2d99af1fb945d4f1511f0040fc3d9e5857c32c97 is missing

**Comment by ge0rg** [comment]
Oh, looks like I had a diverged master commit just to bump tooling. Uploaded it as https://github.com/ge0rg/MemorizingTrustManager/tree/yaxim now.

**Comment by licaon-kter** [comment]
OK, so I remove triplet, installrefferer lines from build.gradle

Then these 3: https://github.com/yaxim-org/yaxim/blob/master/build.gradle#L157

But then it complains about `apply plugin: 'com.android.application'`
```
* What went wrong:
A problem occurred evaluating root project 'org.yaxim.androidclient'.
> Failed to apply plugin [class 'org.gradle.api.plugins.BasePlugin']
   > Could not create service of type OutputFilesRepository using ExecutionGradleServices.createOutputFilesRepository().
```
...and if I remove that... things just fall apart

What am I missing?

**Comment by maathieu** [comment]
bump, F-Droid version is still 9.3.5 and there seems to be a lot of improvement with the newest version.

**Comment by licaon-kter** [comment]
Yep, didn't have the time to navigate all the odd deps needed. :(

**Comment by linsui** [comment]
I got

```
Build file '/builds/linsui/fdroiddata/build/srclib/ge0rg-jxmpp/build.gradle' line: 24
* What went wrong:
A problem occurred evaluating root project 'ge0rg-jxmpp'.
> Failed to apply plugin [id 'org.gradle.java']
   > Could not create task ':animalsnifferCacheMain'.
      > Could not create task of type 'BuildSignatureTask'.
         > org/gradle/api/internal/file/collections/SimpleFileCollection
```
 when building jxmpp with gradle 5.4.1. Am I missing something?

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.yaxim.androidclient.yml#L158
