### ISSUE TITLE
When opening Yaxim it accesses the clipboard

### ISSUE THREAD

**Issue by NCC1701M** [yaxim-org/yaxim#280]
When I open the yaxim Android app I get the information that `yaxim pasted from your clipboard`.

Why does this happen? What happens with the data yaxim gets from the clipboard?

**Comment by ge0rg** [comment]
This is a convenience feature introduced in 0.9.3; if the clipboard contains an xmpp URI or something that looks like a JID, it will be shown as "Add <jid> to contacts..." in the app menu.

The respective code can be found in https://github.com/yaxim-org/yaxim/blob/master/src/org/yaxim/androidclient/MainWindow.java#L318-L327
