### ISSUE TITLE
Implement delivery notifications

### ISSUE THREAD

**Issue by xor-freenet** [yaxim-org/yaxim#60]
Hi,
I'm annoyed by the fact that many people use WhatsApp - it is a yet another proprietary IM protocol, and there are enough of them already.

The only advantage it has over being always-online on Facebook with Jabber is  delivery notifications.
This is especially the case since Facebook rater often loses messages when being used with Jabber clients - I've seen message loss with different clients, so it is probably a problem which can only be fixed by Facebook,  and I doubt that they care.

What COULD be done is the following:
There is a draft for delivery notifications for Jabber and I would be very glad if you implement support for them.

See
http://xmpp.org/extensions/xep-0184.html

Any chance you'll be doing this for the next version?

Thanks,
        "xor"

**Comment by intergleam** [comment]
there is no delivery notification in the current version

**Comment by ge0rg** [comment]
Please elaborate: do you not see delivery notifications for messages that you send? Does your chat partner not see delivery notifications when writing to you?

Are you or is your chat partner using two XMPP clients? Which clients are in use? Delivery notifications must be supported by both sides, and there are certain situations when they don't arrive.

**Comment by intergleam** [comment]
may be you tell me what is the stable combinations for server and partner windows app? Because so far none of the combinations work for me.

**Comment by ge0rg** [comment]
Modern and well-supported Windows clients are probably:

- Gajim - https://gajim.org/
- Swift - https://swift.im/

Both support XEP-0184 delivery receipts. Gajim is a rather complex one, and Swift is aimed at easy use.

**Comment by intergleam** [comment]
I am using Gajim. What about servers? 
I tried dismail.de on both sides but currently with conversations and after a Android loses connection and you have to actually open the app to restore it.

**Comment by ge0rg** [comment]
According to the Conversations compliance tester, dismail.de looks pretty good. I think you should better come into the [yaxim support MUC](https://yax.im/i/#yaxim@chat.yax.im?join) to discuss what's going wrong, as the issue tracker is not the right place for this.
