### ISSUE TITLE
Feature request: XEP-0313 (Message Archive Management)

### ISSUE THREAD

**Issue by jfrederickson** [yaxim-org/yaxim#98]
So I know this was [mentioned previously in a comment](https://github.com/pfleidi/yaxim/issues/73), but I figured I'd give it its own issue here.  Carbons are great to have (yaxim is one of the few clients that support it) but clients will still miss messages sent while you are offline.  Together with [XEP-0059](http://xmpp.org/extensions/xep-0059.html) this could be used for a sort of "infinite scrollback" similar to what Facebook, Hangouts, and the like have.  (For a mobile client you probably do want this, else I believe you'd have to request all history from the server.)

**Comment by delphir-com** [comment]
voting for this one too! really needed.
is there any working alternative for android devices with MAM and Carbons support ?

**Comment by devurandom** [comment]
@delphir-com [Conversations](https://conversations.im/)

**Comment by ge0rg** [comment]
It only took half a decade, but now it's finally there! yaxim with MAM! [APK](https://yaxim.org/archive/builds/yaxim-gl-2019-10-18.apk) and also on [Google Play Beta](https://play.google.com/apps/testing/org.yaxim.androidclient).

This release will automatically enable MAM on your account, if not enabled yet. It will also make MAM notifications silent (for now).

**Comment by readyblue** [comment]
can you please also update your version on F-Droid?

**Comment by Echolon** [comment]
@ge0rg this is finished and can be closed?
